/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-07-12 14:30:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bean.EmployeeDAO;
import com.bean.Employee;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public final class Update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


		Employee emp = null;
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Update</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"text-align:center;\">\r\n");
      out.write("<h1 class=\"sign_in\">Update Employee Details</h1>\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"username\" placeholder=\"Username\" /> \r\n");
      out.write("\t\t<input type=\"submit\" value=\"Search\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');

	if ("POST".equalsIgnoreCase(request.getMethod())) {
		ApplicationContext factory = new ClassPathXmlApplicationContext("beans.xml");
		EmployeeDAO obj = (EmployeeDAO) factory.getBean("empimpl");
		emp = obj.getEmp(request.getParameter("username"));
		
      out.write("\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t<form action=\"update\" method=\"post\" onsubmit=\"return passwordCheck()\">\r\n");
      out.write("\t\tUSERNAME : <input type=\"text\" name=\"username\" placeholder=\"Username\" value=\"");
      out.print(emp.getUsername() );
      out.write("\" readonly />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br> \r\n");
      out.write("\t\tPASSWORD : <input type=\"text\" name=\"password\" id=\"pwd1\" placeholder=\"Password\" value=\"");
      out.print(emp.getPassword() );
      out.write("\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\tCONFIRM PASSWORD : <input type=\"text\" name=\"password2\" id=\"pwd2\" placeholder=\"Confirm Password\" value=\"");
      out.print(emp.getPassword() );
      out.write("\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br> \r\n");
      out.write("\t\tAGE : <input type=\"number\" name=\"age\" placeholder=\"Age\" value=\"");
      out.print(emp.getAge() );
      out.write("\"/>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br> \r\n");
      out.write("\t\tEMAIL : <input type=\"email\" name=\"email\" placeholder=\"Email\" value=\"");
      out.print(emp.getEmail() );
      out.write("\"/>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br> \r\n");
      out.write("\t\tDEPARTMENT : <input type=\"text\" name=\"department\" placeholder=\"Department\" value=\"");
      out.print(emp.getDepartment() );
      out.write("\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\tROLE : <input type=\"text\" name=\"role\" placeholder=\"Role\" value=\"");
      out.print(emp.getRole() );
      out.write("\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br> \r\n");
      out.write("\t\t<input type=\"submit\" value=\"Update\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"reset\" value=\"Reset\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
 
		
	  	
	} else {
	  	System.out.println("Failure");
	}
	
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction passwordCheck(){\r\n");
      out.write("\t\tvar pwd1 = document.getElementById(\"pwd1\").value;\r\n");
      out.write("\t\tvar pwd2 = document.getElementById(\"pwd2\").value;\r\n");
      out.write("\t\tif(pwd1 === pwd2){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\talert(\"Both the password fields are not same !\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
